_target_: src.models.vae.VAEModule

use_ema: true

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 50
  eta_min: 1e-6

encoder_path: /data/hpc/qtung/gen-model-boilerplate/src/ckpt_s256/vq_vae_both/encoder.pth # both
decoder_path: /data/hpc/qtung/gen-model-boilerplate/src/ckpt_s256/vq_vae_both/decoder.pth # both
vq_layer_path: /data/hpc/qtung/gen-model-boilerplate/src/ckpt_s256/vq_vae_both/vq_layer_1024.pth # both

net:
  _target_: src.models.vae.net.VQVAE

  encoder:
    _target_: src.models.components.up_down.Encoder

    in_channels: 4  # Adjusted to match BRATS2020 dataset
    z_channels: ${net.latent_dims[0]}
    base_channels: 64
    block: Residual
    n_layer_blocks: 1
    drop_rate: 0.1
    channel_multipliers: [1, 2, 4]
    attention: Attention
    n_attention_heads: null
    n_attention_layers: null
    double_z: false

  decoder:
    _target_: src.models.components.up_down.Decoder

    out_channels: ${net.encoder.in_channels}
    z_channels: ${net.latent_dims[0]}
    base_channels: ${net.encoder.base_channels}
    block: ${net.encoder.block}
    n_layer_blocks: ${net.encoder.n_layer_blocks}
    drop_rate: ${net.encoder.drop_rate}
    channel_multipliers: ${net.encoder.channel_multipliers}
    attention: ${net.encoder.attention}
    n_attention_heads: ${net.encoder.n_attention_heads}
    n_attention_layers: ${net.encoder.n_attention_layers}

  latent_dims: [4, 32, 32]  # Adjusted to match the configuration

  vq_layer:
    _target_: src.models.vae.net.VectorQuantizer
    num_embeddings: 1024
    embedding_dim: ${net.latent_dims[0]}
    beta: 0.25

criterion: 
  _target_: torch.nn.MSELoss